<H1> Agenda for CS #4,5,6</H1>

<P>
1. Introduction to SciPy Eco system
2. Basics of NumPy
3. Basics of Pandas
4. Data Exploration for a Bike Dataset
5. Visualization using Matplotlib
6. Visualization using Seaborn
7. Introduction to Scikit-lern

</P>

<H2>Introduction to SciPy Ecosystem</H2>

<H3> NumPy, SciPy Library , Matplotlib, IPython SymPy, Pandas</H3>
<P>
1. NumPy - Base N-dimensional

    
</P>

<P> Nympy - Based N- dimensional array Package

- Numpy Stands for Numerical Python
- Numpy is a python library used for working with arrays
- It also has functions for working in domain of linear algebra, fourier transform, and matrices.
- 

- Core python array are heterogenous. But it is homogeneous



Why Uses of Numpy

- In python we have lists that serve the purpose of arrays, but they are slow to process.
- Numpy aims to provide an array object that is up to 50x faster than traditional Python lists.
- The array object in NumPy is called ndarray, it provides a lot of supporting functions.



Lets have hands-on session on:
- Creation of NumPy array
- Properties of NumPy array
- Prepopulated arrays
- 2D arrays
- Ways to access array
- Reshaping
- Computations
- - Arithmetic
  - Comparison
  - Aggregation
  - Boolean
- Note on Linear Algebra and  NumPy arrays 
</P>

Lecture 3.2_Numpy

In [6]:
import array 
my_array = array.array('i',[1,2,3,4])


In [8]:
type(my_array)

array.array

In [10]:
my_float_array = array.array('f',[1.3,1.4])
my_float_array

array('f', [1.2999999523162842, 1.399999976158142])

<b> NumPy arrays</b>

In [17]:
import numpy

In [19]:
import numpy as np

In [23]:
int_list1=[1,2,3,4,5]
np_int_array=np.array(int_list1)
np_int_array


array([1, 2, 3, 4, 5])

In [37]:
float_list = [1.2,3.4,5.7]
np_float_array = np.array(float_list)
np_float_array

array([1.2, 3.4, 5.7])

In [31]:
mixed_list = [1,1.1,2.3,3.7]
np_mixed_list = np.array(mixed_list)# Mixed list converted to all float
np_mixed_list

array([1. , 1.1, 2.3, 3.7])

In [33]:
int_list2=[1,2,3,4,5]
np_int_array=np.array(int_list2,dtype=int)
np_int_array

array([1, 2, 3, 4, 5])

In [23]:
zero_arr = np.array(100)
zero_arr

array(100)

In [25]:
type(zero_arr)

numpy.ndarray

In [29]:
np_twod_array = np.array([[1,2,3],[4,5,6]])
print(np_twod_array)
type(np_twod_array)

[[1 2 3]
 [4 5 6]]


numpy.ndarray

In [33]:
to_back_list = np_twod_array.tolist();
type(to_back_list)

list

In [62]:
twod_array=np.array([[1,2,3],[4,5,6]])
print(twod_array)
type(twod_array)

[[1 2 3]
 [4 5 6]]


numpy.ndarray

In [64]:
to_back_list = ny_py_array.tolist

NameError: name 'ny_py_array' is not defined

<p> Properties of NumPy array</p>